"""
FastAPI backend for the INORCO website chatbot.

This file exposes your existing CrewAI RAG pipeline (agent.py, tools.py, tasks.py, crew.py)
as a simple web API that the website's chat widget can call.

Run locally with:
    uvicorn main:app --reload --port 8000

Then test with:
    http://127.0.0.1:8000/docs   (interactive API docs, auto-generated by FastAPI)
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from crew import crew


app = FastAPI(title="INORCO Chatbot API")


# ---------------------------------------------------------------------------
# CORS (Cross-Origin Resource Sharing)
# ---------------------------------------------------------------------------
# Browsers block a webpage from calling an API on a different domain unless
# that API explicitly allows it. Since your widget will live on
# https://www.inorco.in but your API will live on a different domain
# (e.g. https://your-api.onrender.com), you MUST list inorco.in below.
#
# For local testing you can temporarily use ["*"] (allow everyone), but
# switch to the exact domain before going live.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "https://www.inorco.in",
        "https://inorco.in",
        "http://localhost:3000",   # optional: for local widget testing
    ],
    allow_credentials=True,
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Request / Response schemas
# ---------------------------------------------------------------------------
class ChatRequest(BaseModel):
    question: str


class ChatResponse(BaseModel):
    answer: str


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------
@app.get("/")
def health_check():
    """Simple endpoint to confirm the server is alive. Visit this URL in a browser."""
    return {"status": "ok", "message": "INORCO chatbot API is running."}


@app.post("/chat", response_model=ChatResponse)
def chat(request: ChatRequest):
    """
    Main chat endpoint. The website widget sends {"question": "..."} here
    and receives back {"answer": "..."}.
    """
    question = request.question.strip()

    if not question:
        raise HTTPException(status_code=400, detail="Question cannot be empty.")

    try:
        result = crew.kickoff({"question": question})
        return ChatResponse(answer=str(result))
    except Exception as e:
        # Never leak internal errors/API keys to the frontend — log server-side instead.
        print(f"ERROR while processing question '{question}': {e}")
        raise HTTPException(
            status_code=500,
            detail="Something went wrong while generating the answer. Please try again."
        )